create table items (
    id bigint generated by default as identity,
    description varchar(150),
    name varchar(50) not null,
    price decimal(19,2) not null,
    restaurant_id bigint not null,
    primary key (id)
);

alter table items 
    add constraint fk_item_restaurant 
    foreign key (restaurant_id) 
    references restaurants;
