create table orders (
    id bigint generated by default as identity,
    date_time timestamp,
    customer_id bigint not null,
    restaurant_id bigint not null,
    primary key (id)
);

alter table orders 
    add constraint fk_order_restaurant 
    foreign key (restaurant_id) 
    references restaurants;
    
alter table orders 
    add constraint fk_order_customer 
    foreign key (customer_id) 
    references customers;