create table order_items (
    id bigint generated by default as identity,
    quantity decimal(19,2),
    unit_price decimal(19,2),
    item_id bigint not null,
    order_id bigint not null,
    primary key (id)
);

alter table order_items 
    add constraint fk_orderitem_item 
    foreign key (item_id) 
    references items;
alter table order_items 
    add constraint fk_orderitem_order 
    foreign key (order_id) 
    references orders;
alter table orders 
    add constraint fk_orderitem_customer 
    foreign key (customer_id) 
    references customers;