create table items (
    id bigint generated by default as identity,
    description varchar(255),
    name varchar(255),
    price decimal(19,2),
    restaurant_id bigint,
    primary key (id)
)

alter table item 
    add constraint fk_item_restaurant 
    foreign key (restaurant_id) 
    references restaurant
